/**
 * ============================================================
 * TrustSheild OS™ — Demo Data Seed
 * Run 2 — Command Dashboard Structure
 * Powered by 4P3X Intelligent AI™  ·  Created by Kyzel Kreates™
 * ============================================================
 *
 * ⚠️  DEMO DATA ONLY — All records are fictional.
 *     No real persons, businesses, or events are represented.
 *     This data is clearly marked as demo/simulation throughout the UI.
 *
 * Seeded through useTrustStore.seedDemoData() — never hardcoded
 * directly into UI components.
 * ============================================================
 */

// ─── Helpers ─────────────────────────────────────────────────
const ago = (minutes) => new Date(Date.now() - minutes * 60 * 1000).toISOString()

// ─── CASES — Active Reputation Risks ─────────────────────────
export const DEMO_CASES = [
  {
    id: 'case-001',
    title: 'Negative Review Spike — Meridian Cafe',
    client: 'Meridian Cafe Group',
    riskLevel: 'High',
    source: 'Review Platform',
    channel: 'Google Reviews / Yelp',
    status: 'Action Needed',
    assignedPwaId: 'pwa-001',
    assignedResponder: 'Sarah K.',
    summary: 'Coordinated negative reviews appearing across Google and Yelp following a staff dispute. 14 new 1-star reviews in 72 hours. Response team mobilised.',
    tags: ['reviews', 'local-business', 'coordinated'],
    createdAt: ago(4320),
    updatedAt: ago(45),
    _demo: true,
  },
  {
    id: 'case-002',
    title: 'Social Media Complaint Gaining Traction',
    client: 'Vantage Fintech Ltd',
    riskLevel: 'Critical',
    source: 'Social Media',
    channel: 'X (Twitter) / LinkedIn',
    status: 'Escalated',
    assignedPwaId: 'pwa-002',
    assignedResponder: 'Marcus T.',
    summary: 'Former customer thread alleging data handling concerns going viral. Thread has 2.4K reshares. Legal team notified. PR holding statement drafted.',
    tags: ['social-media', 'viral', 'fintech', 'legal'],
    createdAt: ago(2880),
    updatedAt: ago(18),
    _demo: true,
  },
  {
    id: 'case-003',
    title: 'Incorrect Public Claim — Press Coverage',
    client: 'Elara Health Clinic',
    riskLevel: 'Medium',
    source: 'News',
    channel: 'Local News Website',
    status: 'Response Drafted',
    assignedPwaId: 'pwa-003',
    assignedResponder: 'Dr. Priya N.',
    summary: 'Regional news article contains factual inaccuracy about clinic\'s accreditation status. Correction request submitted. Response approved by legal. Awaiting publication.',
    tags: ['press', 'correction', 'healthcare'],
    createdAt: ago(1440),
    updatedAt: ago(90),
    _demo: true,
  },
  {
    id: 'case-004',
    title: 'Customer Service Failure — Public Apology Required',
    client: 'Oakhaven Hotels',
    riskLevel: 'Medium',
    source: 'Customer Complaint',
    channel: 'TripAdvisor / Instagram',
    status: 'Monitoring',
    assignedPwaId: 'pwa-001',
    assignedResponder: 'Sarah K.',
    summary: 'High-profile guest complaint about wedding booking cancellation. Guest has 45K Instagram followers and has posted publicly. Apology response being prepared.',
    tags: ['hospitality', 'influencer', 'apology'],
    createdAt: ago(720),
    updatedAt: ago(120),
    _demo: true,
  },
  {
    id: 'case-005',
    title: 'Internal Incident — Controlled Stakeholder Update',
    client: 'NordVista Capital',
    riskLevel: 'High',
    source: 'Internal Escalation',
    channel: 'Internal / Investor Relations',
    status: 'Monitoring',
    assignedPwaId: 'pwa-004',
    assignedResponder: 'James W.',
    summary: 'Regulatory inquiry received. Communications being managed internally. Investor relations update being prepared. External disclosure protocol active.',
    tags: ['regulatory', 'investor-relations', 'confidential'],
    createdAt: ago(360),
    updatedAt: ago(30),
    _demo: true,
  },
  {
    id: 'case-006',
    title: 'Creator Reputation Concern — Misquote',
    client: 'Layla Voss (Public Figure)',
    riskLevel: 'Low',
    source: 'Social Media',
    channel: 'Instagram / TikTok',
    status: 'Monitoring',
    assignedPwaId: 'pwa-002',
    assignedResponder: 'Marcus T.',
    summary: 'Out-of-context quote from old podcast clipped and circulating. Creator monitoring situation. No action required yet — watching engagement trends.',
    tags: ['creator', 'misquote', 'monitoring'],
    createdAt: ago(180),
    updatedAt: ago(60),
    _demo: true,
  },
  {
    id: 'case-007',
    title: 'Agency Client — Active PR Risk Assessment',
    client: 'Sable & Partners Agency / Client X',
    riskLevel: 'Medium',
    source: 'Community',
    channel: 'Community Forum / Reddit',
    status: 'Monitoring',
    assignedPwaId: 'pwa-003',
    assignedResponder: 'Dr. Priya N.',
    summary: 'Forum discussion about agency client\'s past campaign resurfacing. Community sentiment neutral-to-negative. No viral spread yet. Pre-emptive response plan prepared.',
    tags: ['agency', 'community', 'pr-risk'],
    createdAt: ago(90),
    updatedAt: ago(15),
    _demo: true,
  },
]

// ─── PWAs — Connected Response Contacts ──────────────────────
export const DEMO_PWAS = [
  {
    id: 'pwa-001',
    displayName: 'Sarah K.',
    role: 'PR Lead',
    organisation: 'Meridian Cafe Group / Oakhaven Hotels',
    pwaIdPlaceholder: 'PWA-ID-001 (Run 5)',
    syncStatus: 'Demo',
    lastCheckIn: ago(25),
    assignedCases: ['case-001', 'case-004'],
    pendingTasks: 3,
    configStatus: 'Demo Mode',
    avatar: 'SK',
    _demo: true,
  },
  {
    id: 'pwa-002',
    displayName: 'Marcus T.',
    role: 'Responder',
    organisation: 'Vantage Fintech / Layla Voss',
    pwaIdPlaceholder: 'PWA-ID-002 (Run 5)',
    syncStatus: 'Demo',
    lastCheckIn: ago(8),
    assignedCases: ['case-002', 'case-006'],
    pendingTasks: 5,
    configStatus: 'Demo Mode',
    avatar: 'MT',
    _demo: true,
  },
  {
    id: 'pwa-003',
    displayName: 'Dr. Priya N.',
    role: 'Legal Contact',
    organisation: 'Elara Health / Sable Agency',
    pwaIdPlaceholder: 'PWA-ID-003 (Run 5)',
    syncStatus: 'Pending',
    lastCheckIn: ago(95),
    assignedCases: ['case-003', 'case-007'],
    pendingTasks: 2,
    configStatus: 'Demo Mode',
    avatar: 'PN',
    _demo: true,
  },
  {
    id: 'pwa-004',
    displayName: 'James W.',
    role: 'Staff Member',
    organisation: 'NordVista Capital',
    pwaIdPlaceholder: 'PWA-ID-004 (Run 5)',
    syncStatus: 'Demo',
    lastCheckIn: ago(12),
    assignedCases: ['case-005'],
    pendingTasks: 1,
    configStatus: 'Demo Mode',
    avatar: 'JW',
    _demo: true,
  },
  {
    id: 'pwa-005',
    displayName: 'Agency Contact',
    role: 'Agency Contact',
    organisation: 'Sable & Partners (Unconfirmed)',
    pwaIdPlaceholder: 'PWA-ID-005 (Run 5)',
    syncStatus: 'Offline',
    lastCheckIn: ago(480),
    assignedCases: [],
    pendingTasks: 0,
    configStatus: 'Not Configured',
    avatar: 'AC',
    _demo: true,
  },
]

// ─── TASKS — Sent to PWAs ─────────────────────────────────────
export const DEMO_TASKS = [
  {
    id: 'task-001',
    title: 'Confirm: Holding Statement Received',
    type: 'Confirm Update Received',
    linkedCaseId: 'case-002',
    assignedPwaId: 'pwa-002',
    assignedTo: 'Marcus T.',
    status: 'Completed',
    priority: 'High',
    sentAt: ago(90),
    completedAt: ago(72),
    notes: 'Confirmed via PWA response at 14:32.',
    _demo: true,
  },
  {
    id: 'task-002',
    title: 'Submit Situation Update — Review Spike',
    type: 'Submit Situation Update',
    linkedCaseId: 'case-001',
    assignedPwaId: 'pwa-001',
    assignedTo: 'Sarah K.',
    status: 'In Progress',
    priority: 'High',
    sentAt: ago(60),
    completedAt: null,
    notes: 'Awaiting update from on-site team.',
    _demo: true,
  },
  {
    id: 'task-003',
    title: 'Upload Evidence — Screenshots of Reviews',
    type: 'Upload Evidence / Notes',
    linkedCaseId: 'case-001',
    assignedPwaId: 'pwa-001',
    assignedTo: 'Sarah K.',
    status: 'Pending',
    priority: 'Medium',
    sentAt: ago(45),
    completedAt: null,
    notes: null,
    _demo: true,
  },
  {
    id: 'task-004',
    title: 'Approve Draft: Correction Response to News',
    type: 'Approve Draft Response',
    linkedCaseId: 'case-003',
    assignedPwaId: 'pwa-003',
    assignedTo: 'Dr. Priya N.',
    status: 'Pending',
    priority: 'High',
    sentAt: ago(30),
    completedAt: null,
    notes: 'Legal review sign-off required before publication.',
    _demo: true,
  },
  {
    id: 'task-005',
    title: 'Send Availability Check-in — NordVista',
    type: 'Send Availability Check-in',
    linkedCaseId: 'case-005',
    assignedPwaId: 'pwa-004',
    assignedTo: 'James W.',
    status: 'Completed',
    priority: 'Medium',
    sentAt: ago(120),
    completedAt: ago(110),
    notes: 'Available and standing by.',
    _demo: true,
  },
  {
    id: 'task-006',
    title: 'Log Social Media Issue — Viral Thread',
    type: 'Log Social Media Issue',
    linkedCaseId: 'case-002',
    assignedPwaId: 'pwa-002',
    assignedTo: 'Marcus T.',
    status: 'Completed',
    priority: 'Critical',
    sentAt: ago(200),
    completedAt: ago(185),
    notes: 'Thread URL and screenshot logged.',
    _demo: true,
  },
  {
    id: 'task-007',
    title: 'Request Escalation — Legal Team Alert',
    type: 'Request Escalation',
    linkedCaseId: 'case-002',
    assignedPwaId: 'pwa-002',
    assignedTo: 'Marcus T.',
    status: 'In Progress',
    priority: 'Critical',
    sentAt: ago(40),
    completedAt: null,
    notes: 'Legal team being looped in.',
    _demo: true,
  },
  {
    id: 'task-008',
    title: 'Add Customer Feedback — Hotel Guest',
    type: 'Add Customer / Witness Feedback',
    linkedCaseId: 'case-004',
    assignedPwaId: 'pwa-001',
    assignedTo: 'Sarah K.',
    status: 'Pending',
    priority: 'Medium',
    sentAt: ago(20),
    completedAt: null,
    notes: null,
    _demo: true,
  },
]

// ─── TIMELINE — Evidence & Crisis Events ─────────────────────
export const DEMO_TIMELINE = [
  {
    id: 'evt-001',
    title: 'Case Opened: Negative Review Spike',
    linkedCaseId: 'case-001',
    type: 'Note',
    evidenceType: 'Internal Note',
    submittedBy: 'Dashboard Admin',
    source: 'Dashboard',
    ts: ago(4320),
    content: 'Case opened. Monitoring review platforms. Initial triage complete.',
    _demo: true,
  },
  {
    id: 'evt-002',
    title: 'Screenshot: Viral Thread Captured',
    linkedCaseId: 'case-002',
    type: 'Evidence',
    evidenceType: 'Screenshot',
    submittedBy: 'Marcus T.',
    source: 'PWA Submission',
    ts: ago(2800),
    content: 'Screenshot of original thread at 2.1K reshares. Archived for evidence.',
    _demo: true,
  },
  {
    id: 'evt-003',
    title: 'Legal Notified — Vantage Fintech',
    linkedCaseId: 'case-002',
    type: 'Note',
    evidenceType: 'Internal Note',
    submittedBy: 'Dashboard Admin',
    source: 'Dashboard',
    ts: ago(2700),
    content: 'Legal team briefed. External disclosure protocol activated. Holding statement drafted.',
    _demo: true,
  },
  {
    id: 'evt-004',
    title: 'Press Article Identified — Elara Health',
    linkedCaseId: 'case-003',
    type: 'Evidence',
    evidenceType: 'Link',
    submittedBy: 'Dr. Priya N.',
    source: 'PWA Submission',
    ts: ago(1440),
    content: 'URL to article with inaccuracy shared via PWA. Article archived.',
    _demo: true,
  },
  {
    id: 'evt-005',
    title: 'Customer Post Logged — Oakhaven Hotels',
    linkedCaseId: 'case-004',
    type: 'Evidence',
    evidenceType: 'Public Post',
    submittedBy: 'Sarah K.',
    source: 'PWA Submission',
    ts: ago(720),
    content: 'Instagram post by affected guest with 45K followers. Screenshot archived.',
    _demo: true,
  },
  {
    id: 'evt-006',
    title: 'Risk Level Escalated — Vantage Case',
    linkedCaseId: 'case-002',
    type: 'Escalation',
    evidenceType: 'Internal Note',
    submittedBy: 'Dashboard Admin',
    source: 'Dashboard',
    ts: ago(600),
    content: 'Thread reshares exceeded 2,000. Risk level raised from High to Critical.',
    _demo: true,
  },
  {
    id: 'evt-007',
    title: 'Regulatory Inquiry Received — NordVista',
    linkedCaseId: 'case-005',
    type: 'Evidence',
    evidenceType: 'Internal Note',
    submittedBy: 'James W.',
    source: 'PWA Submission',
    ts: ago(360),
    content: 'Formal inquiry received via certified post. Reference: NVC/REG/2026-041. Acknowledged.',
    _demo: true,
  },
  {
    id: 'evt-008',
    title: 'Monitoring Active — Creator Misquote',
    linkedCaseId: 'case-006',
    type: 'Note',
    evidenceType: 'Note',
    submittedBy: 'Marcus T.',
    source: 'PWA Submission',
    ts: ago(175),
    content: 'Clip circulating on TikTok. Engagement not accelerating. No amplification detected.',
    _demo: true,
  },
]

// ─── DRAFTS — Response Drafts ─────────────────────────────────
export const DEMO_DRAFTS = [
  {
    id: 'draft-001',
    title: 'Holding Statement — Vantage Fintech Social Thread',
    linkedCaseId: 'case-002',
    intendedChannel: 'X (Twitter) — Official Account',
    tone: 'Holding Statement',
    status: 'Needs Review',
    owner: 'Marcus T.',
    aiAdvisory: true,
    content: 'We are aware of the concerns raised online and take all feedback seriously. Our team is reviewing the matter and will provide a full update within 24 hours. We are committed to transparency and are working to address this directly. [DRAFT — HUMAN REVIEW REQUIRED]',
    createdAt: ago(2650),
    updatedAt: ago(120),
    _demo: true,
  },
  {
    id: 'draft-002',
    title: 'Correction Request — Elara Health Press Article',
    linkedCaseId: 'case-003',
    intendedChannel: 'Email to Editor / Publication Contact',
    tone: 'Corrective',
    status: 'Approved',
    owner: 'Dr. Priya N.',
    aiAdvisory: true,
    content: 'Dear [Editor], We write to respectfully request a correction to your article published on [date]. The article states [INACCURACY]. The factual position is [CORRECTION]. We would appreciate an update at your earliest convenience. [DRAFT — APPROVED FOR SEND]',
    createdAt: ago(1400),
    updatedAt: ago(85),
    _demo: true,
  },
  {
    id: 'draft-003',
    title: 'Public Apology — Oakhaven Hotels Guest',
    linkedCaseId: 'case-004',
    intendedChannel: 'Instagram Public Comment + TripAdvisor',
    tone: 'Apologetic',
    status: 'Draft',
    owner: 'Sarah K.',
    aiAdvisory: true,
    content: 'We sincerely apologise for the disruption caused to your wedding booking. This falls far short of the standard we hold ourselves to. We have reached out directly to arrange a personal conversation and to make this right. [DRAFT — NEEDS REVIEW]',
    createdAt: ago(680),
    updatedAt: ago(200),
    _demo: true,
  },
  {
    id: 'draft-004',
    title: 'Investor Update — NordVista Capital',
    linkedCaseId: 'case-005',
    intendedChannel: 'Email — Investor Relations List',
    tone: 'Formal',
    status: 'Legal Review Needed',
    owner: 'James W.',
    aiAdvisory: true,
    content: 'Dear Investors, We wish to proactively inform you of a regulatory inquiry we received on [date]. We are cooperating fully and are confident in our compliance position. Further updates will follow. This communication is confidential. [DRAFT — LEGAL REVIEW REQUIRED]',
    createdAt: ago(330),
    updatedAt: ago(30),
    _demo: true,
  },
]

// ─── STAKEHOLDER UPDATES ──────────────────────────────────────
export const DEMO_UPDATES = [
  {
    id: 'upd-001',
    title: 'Internal Team Briefing — Review Spike',
    linkedCaseId: 'case-001',
    audience: 'Internal Team',
    status: 'Sent',
    owner: 'Dashboard Admin',
    lastSent: ago(200),
    pending: false,
    notes: 'All team members briefed on situation. Monitoring schedule assigned.',
    _demo: true,
  },
  {
    id: 'upd-002',
    title: 'Client Holding Update — Vantage Fintech',
    linkedCaseId: 'case-002',
    audience: 'Client (Vantage Fintech Leadership)',
    status: 'Sent',
    owner: 'Marcus T.',
    lastSent: ago(400),
    pending: false,
    notes: 'Client acknowledged update. Awaiting outcome of legal review.',
    _demo: true,
  },
  {
    id: 'upd-003',
    title: 'PR Team Briefing — Correction Status',
    linkedCaseId: 'case-003',
    audience: 'PR Team',
    status: 'Pending',
    owner: 'Dr. Priya N.',
    lastSent: null,
    pending: true,
    notes: 'Awaiting legal sign-off before sending.',
    _demo: true,
  },
  {
    id: 'upd-004',
    title: 'Leadership Notification — Regulatory Inquiry',
    linkedCaseId: 'case-005',
    audience: 'Executive Leadership',
    status: 'Sent',
    owner: 'James W.',
    lastSent: ago(300),
    pending: false,
    notes: 'Board notified. Confidentiality protocol in place.',
    _demo: true,
  },
  {
    id: 'upd-005',
    title: 'Customer Apology Follow-up — Oakhaven',
    linkedCaseId: 'case-004',
    audience: 'Affected Customer',
    status: 'Pending',
    owner: 'Sarah K.',
    lastSent: null,
    pending: true,
    notes: 'Awaiting draft approval before sending to guest.',
    _demo: true,
  },
]

// ─── FEED — Live Update Feed ──────────────────────────────────
export const DEMO_FEED = [
  {
    id: 'feed-001',
    type: 'task_complete',
    icon: 'CheckCircle',
    color: 'green',
    text: 'Marcus T. confirmed holding statement received',
    sub: 'Vantage Fintech · Task #001',
    ts: ago(72),
    _demo: true,
  },
  {
    id: 'feed-002',
    type: 'evidence',
    icon: 'FileText',
    color: 'gold',
    text: 'Screenshot evidence submitted via Response PWA',
    sub: 'Vantage Fintech viral thread · Marcus T.',
    ts: ago(185),
    _demo: true,
  },
  {
    id: 'feed-003',
    type: 'escalation',
    icon: 'AlertTriangle',
    color: 'red',
    text: 'Risk level escalated to Critical — Vantage Fintech',
    sub: 'Reshares exceeded 2,000 · Dashboard Admin',
    ts: ago(600),
    _demo: true,
  },
  {
    id: 'feed-004',
    type: 'checkin',
    icon: 'UserCheck',
    color: 'green',
    text: 'James W. availability check-in completed',
    sub: 'NordVista Capital · PWA-004',
    ts: ago(110),
    _demo: true,
  },
  {
    id: 'feed-005',
    type: 'draft',
    icon: 'FileEdit',
    color: 'purple',
    text: 'Draft response awaiting approval — Correction Request',
    sub: 'Elara Health · Dr. Priya N.',
    ts: ago(85),
    _demo: true,
  },
  {
    id: 'feed-006',
    type: 'update_sent',
    icon: 'Send',
    color: 'silver',
    text: 'Stakeholder update sent to Vantage Fintech leadership',
    sub: 'Client holding update · Marcus T.',
    ts: ago(400),
    _demo: true,
  },
  {
    id: 'feed-007',
    type: 'task_pending',
    icon: 'Clock',
    color: 'gold',
    text: 'Task pending: Upload evidence — Review screenshots',
    sub: 'Meridian Cafe Group · Sarah K.',
    ts: ago(45),
    _demo: true,
  },
  {
    id: 'feed-008',
    type: 'evidence',
    icon: 'MapPin',
    color: 'gold',
    text: 'Regulatory inquiry reference logged by responder',
    sub: 'NordVista Capital · James W.',
    ts: ago(360),
    _demo: true,
  },
  {
    id: 'feed-009',
    type: 'monitoring',
    icon: 'Eye',
    color: 'silver',
    text: 'Creator misquote clip — no amplification detected',
    sub: 'Layla Voss · Marcus T.',
    ts: ago(175),
    _demo: true,
  },
  {
    id: 'feed-010',
    type: 'task_complete',
    icon: 'CheckCircle',
    color: 'green',
    text: 'Social media issue logged — viral thread archived',
    sub: 'Vantage Fintech · Task #006 · Marcus T.',
    ts: ago(185),
    _demo: true,
  },
]

// ─── Composed export ──────────────────────────────────────────
export const DEMO_DATA = {
  cases:     DEMO_CASES,
  tasks:     DEMO_TASKS,
  pwas:      DEMO_PWAS,
  timeline:  DEMO_TIMELINE,
  drafts:    DEMO_DRAFTS,
  updates:   DEMO_UPDATES,
  feedItems: DEMO_FEED,
}

export default DEMO_DATA
