/**
 * ============================================================
 * TrustSheild OS™ — Demo Data Seed
 * Run 2 — Command Dashboard Structure
 * Powered by 4P3X Intelligent AI™  ·  Created by Kyzel Kreates™
 * ============================================================
 *
 * ⚠️  DEMO DATA ONLY — All records are fictional.
 *     No real persons, businesses, or events are represented.
 *     This data is clearly marked as demo/simulation throughout the UI.
 *
 * Seeded through useTrustStore.seedDemoData() — never hardcoded
 * directly into UI components.
 * ============================================================
 */

// ─── Helpers ─────────────────────────────────────────────────
const ago = (minutes) => new Date(Date.now() - minutes * 60 * 1000).toISOString()

// ─── CASES — Active Reputation Risks ─────────────────────────
export const DEMO_CASES = [
  {
    id: 'case-001',
    title: 'Negative Review Spike — Meridian Cafe',
    client: 'Meridian Cafe Group',
    riskLevel: 'High',
    source: 'Review Platform',
    channel: 'Google Reviews / Yelp',
    status: 'Action Needed',
    assignedPwaId: 'pwa-001',
    assignedResponder: 'Sarah K.',
    summary: 'Coordinated negative reviews appearing across Google and Yelp following a staff dispute. 14 new 1-star reviews in 72 hours. Response team mobilised.',
    tags: ['reviews', 'local-business', 'coordinated'],
    createdAt: ago(4320),
    updatedAt: ago(45),
    _demo: true,
  },
  {
    id: 'case-002',
    title: 'Social Media Complaint Gaining Traction',
    client: 'Vantage Fintech Ltd',
    riskLevel: 'Critical',
    source: 'Social Media',
    channel: 'X (Twitter) / LinkedIn',
    status: 'Escalated',
    assignedPwaId: 'pwa-002',
    assignedResponder: 'Marcus T.',
    summary: 'Former customer thread alleging data handling concerns going viral. Thread has 2.4K reshares. Legal team notified. PR holding statement drafted.',
    tags: ['social-media', 'viral', 'fintech', 'legal'],
    createdAt: ago(2880),
    updatedAt: ago(18),
    _demo: true,
  },
  {
    id: 'case-003',
    title: 'Incorrect Public Claim — Press Coverage',
    client: 'Elara Health Clinic',
    riskLevel: 'Medium',
    source: 'News',
    channel: 'Local News Website',
    status: 'Response Drafted',
    assignedPwaId: 'pwa-003',
    assignedResponder: 'Dr. Priya N.',
    summary: 'Regional news article contains factual inaccuracy about clinic\'s accreditation status. Correction request submitted. Response approved by legal. Awaiting publication.',
    tags: ['press', 'correction', 'healthcare'],
    createdAt: ago(1440),
    updatedAt: ago(90),
    _demo: true,
  },
  {
    id: 'case-004',
    title: 'Customer Service Failure — Public Apology Required',
    client: 'Oakhaven Hotels',
    riskLevel: 'Medium',
    source: 'Customer Complaint',
    channel: 'TripAdvisor / Instagram',
    status: 'Monitoring',
    assignedPwaId: 'pwa-001',
    assignedResponder: 'Sarah K.',
    summary: 'High-profile guest complaint about wedding booking cancellation. Guest has 45K Instagram followers and has posted publicly. Apology response being prepared.',
    tags: ['hospitality', 'influencer', 'apology'],
    createdAt: ago(720),
    updatedAt: ago(120),
    _demo: true,
  },
  {
    id: 'case-005',
    title: 'Internal Incident — Controlled Stakeholder Update',
    client: 'NordVista Capital',
    riskLevel: 'High',
    source: 'Internal Escalation',
    channel: 'Internal / Investor Relations',
    status: 'Monitoring',
    assignedPwaId: 'pwa-004',
    assignedResponder: 'James W.',
    summary: 'Regulatory inquiry received. Communications being managed internally. Investor relations update being prepared. External disclosure protocol active.',
    tags: ['regulatory', 'investor-relations', 'confidential'],
    createdAt: ago(360),
    updatedAt: ago(30),
    _demo: true,
  },
  {
    id: 'case-006',
    title: 'Creator Reputation Concern — Misquote',
    client: 'Layla Voss (Public Figure)',
    riskLevel: 'Low',
    source: 'Social Media',
    channel: 'Instagram / TikTok',
    status: 'Monitoring',
    assignedPwaId: 'pwa-002',
    assignedResponder: 'Marcus T.',
    summary: 'Out-of-context quote from old podcast clipped and circulating. Creator monitoring situation. No action required yet — watching engagement trends.',
    tags: ['creator', 'misquote', 'monitoring'],
    createdAt: ago(180),
    updatedAt: ago(60),
    _demo: true,
  },
  {
    id: 'case-007',
    title: 'Agency Client — Active PR Risk Assessment',
    client: 'Sable & Partners Agency / Client X',
    riskLevel: 'Medium',
    source: 'Community',
    channel: 'Community Forum / Reddit',
    status: 'Monitoring',
    assignedPwaId: 'pwa-003',
    assignedResponder: 'Dr. Priya N.',
    summary: 'Forum discussion about agency client\'s past campaign resurfacing. Community sentiment neutral-to-negative. No viral spread yet. Pre-emptive response plan prepared.',
    tags: ['agency', 'community', 'pr-risk'],
    createdAt: ago(90),
    updatedAt: ago(15),
    _demo: true,
  },
]

// ─── PWAs — Connected Response Contacts ──────────────────────
export const DEMO_PWAS = [
  {
    id: 'pwa-001',
    displayName: 'Sarah K.',
    role: 'PR Lead',
    organisation: 'Meridian Cafe Group / Oakhaven Hotels',
    pwaIdPlaceholder: 'PWA-ID-001 (Run 5)',
    syncStatus: 'Demo',
    lastCheckIn: ago(25),
    assignedCases: ['case-001', 'case-004'],
    pendingTasks: 3,
    configStatus: 'Demo Mode',
    avatar: 'SK',
    _demo: true,
  },
  {
    id: 'pwa-002',
    displayName: 'Marcus T.',
    role: 'Responder',
    organisation: 'Vantage Fintech / Layla Voss',
    pwaIdPlaceholder: 'PWA-ID-002 (Run 5)',
    syncStatus: 'Demo',
    lastCheckIn: ago(8),
    assignedCases: ['case-002', 'case-006'],
    pendingTasks: 5,
    configStatus: 'Demo Mode',
    avatar: 'MT',
    _demo: true,
  },
  {
    id: 'pwa-003',
    displayName: 'Dr. Priya N.',
    role: 'Legal Contact',
    organisation: 'Elara Health / Sable Agency',
    pwaIdPlaceholder: 'PWA-ID-003 (Run 5)',
    syncStatus: 'Pending',
    lastCheckIn: ago(95),
    assignedCases: ['case-003', 'case-007'],
    pendingTasks: 2,
    configStatus: 'Demo Mode',
    avatar: 'PN',
    _demo: true,
  },
  {
    id: 'pwa-004',
    displayName: 'James W.',
    role: 'Staff Member',
    organisation: 'NordVista Capital',
    pwaIdPlaceholder: 'PWA-ID-004 (Run 5)',
    syncStatus: 'Demo',
    lastCheckIn: ago(12),
    assignedCases: ['case-005'],
    pendingTasks: 1,
    configStatus: 'Demo Mode',
    avatar: 'JW',
    _demo: true,
  },
  {
    id: 'pwa-005',
    displayName: 'Agency Contact',
    role: 'Agency Contact',
    organisation: 'Sable & Partners (Unconfirmed)',
    pwaIdPlaceholder: 'PWA-ID-005 (Run 5)',
    syncStatus: 'Offline',
    lastCheckIn: ago(480),
    assignedCases: [],
    pendingTasks: 0,
    configStatus: 'Not Configured',
    avatar: 'AC',
    _demo: true,
  },
]

// ─── TASKS — Sent to PWAs ─────────────────────────────────────
export const DEMO_TASKS = [
  {
    id: 'task-001',
    title: 'Confirm: Holding Statement Received',
    type: 'Confirm Update Received',
    linkedCaseId: 'case-002',
    assignedPwaId: 'pwa-002',
    assignedTo: 'Marcus T.',
    status: 'Completed',
    priority: 'High',
    sentAt: ago(90),
    completedAt: ago(72),
    notes: 'Confirmed via PWA response at 14:32.',
    _demo: true,
  },
  {
    id: 'task-002',
    title: 'Submit Situation Update — Review Spike',
    type: 'Submit Situation Update',
    linkedCaseId: 'case-001',
    assignedPwaId: 'pwa-001',
    assignedTo: 'Sarah K.',
    status: 'In Progress',
    priority: 'High',
    sentAt: ago(60),
    completedAt: null,
    notes: 'Awaiting update from on-site team.',
    _demo: true,
  },
  {
    id: 'task-003',
    title: 'Upload Evidence — Screenshots of Reviews',
    type: 'Upload Evidence / Notes',
    linkedCaseId: 'case-001',
    assignedPwaId: 'pwa-001',
    assignedTo: 'Sarah K.',
    status: 'Pending',
    priority: 'Medium',
    sentAt: ago(45),
    completedAt: null,
    notes: null,
    _demo: true,
  },
  {
    id: 'task-004',
    title: 'Approve Draft: Correction Response to News',
    type: 'Approve Draft Response',
    linkedCaseId: 'case-003',
    assignedPwaId: 'pwa-003',
    assignedTo: 'Dr. Priya N.',
    status: 'Pending',
    priority: 'High',
    sentAt: ago(30),
    completedAt: null,
    notes: 'Legal review sign-off required before publication.',
    _demo: true,
  },
  {
    id: 'task-005',
    title: 'Send Availability Check-in — NordVista',
    type: 'Send Availability Check-in',
    linkedCaseId: 'case-005',
    assignedPwaId: 'pwa-004',
    assignedTo: 'James W.',
    status: 'Completed',
    priority: 'Medium',
    sentAt: ago(120),
    completedAt: ago(110),
    notes: 'Available and standing by.',
    _demo: true,
  },
  {
    id: 'task-006',
    title: 'Log Social Media Issue — Viral Thread',
    type: 'Log Social Media Issue',
    linkedCaseId: 'case-002',
    assignedPwaId: 'pwa-002',
    assignedTo: 'Marcus T.',
    status: 'Completed',
    priority: 'Critical',
    sentAt: ago(200),
    completedAt: ago(185),
    notes: 'Thread URL and screenshot logged.',
    _demo: true,
  },
  {
    id: 'task-007',
    title: 'Request Escalation — Legal Team Alert',
    type: 'Request Escalation',
    linkedCaseId: 'case-002',
    assignedPwaId: 'pwa-002',
    assignedTo: 'Marcus T.',
    status: 'In Progress',
    priority: 'Critical',
    sentAt: ago(40),
    completedAt: null,
    notes: 'Legal team being looped in.',
    _demo: true,
  },
  {
    id: 'task-008',
    title: 'Add Customer Feedback — Hotel Guest',
    type: 'Add Customer / Witness Feedback',
    linkedCaseId: 'case-004',
    assignedPwaId: 'pwa-001',
    assignedTo: 'Sarah K.',
    status: 'Pending',
    priority: 'Medium',
    sentAt: ago(20),
    completedAt: null,
    notes: null,
    _demo: true,
  },
]

// ─── TIMELINE — Evidence & Crisis Events ─────────────────────
export const DEMO_TIMELINE = [
  {
    id: 'evt-001',
    title: 'Case Opened: Negative Review Spike',
    linkedCaseId: 'case-001',
    type: 'Note',
    evidenceType: 'Internal Note',
    submittedBy: 'Dashboard Admin',
    source: 'Dashboard',
    ts: ago(4320),
    content: 'Case opened. Monitoring review platforms. Initial triage complete.',
    _demo: true,
  },
  {
    id: 'evt-002',
    title: 'Screenshot: Viral Thread Captured',
    linkedCaseId: 'case-002',
    type: 'Evidence',
    evidenceType: 'Screenshot',
    submittedBy: 'Marcus T.',
    source: 'PWA Submission',
    ts: ago(2800),
    content: 'Screenshot of original thread at 2.1K reshares. Archived for evidence.',
    _demo: true,
  },
  {
    id: 'evt-003',
    title: 'Legal Notified — Vantage Fintech',
    linkedCaseId: 'case-002',
    type: 'Note',
    evidenceType: 'Internal Note',
    submittedBy: 'Dashboard Admin',
    source: 'Dashboard',
    ts: ago(2700),
    content: 'Legal team briefed. External disclosure protocol activated. Holding statement drafted.',
    _demo: true,
  },
  {
    id: 'evt-004',
    title: 'Press Article Identified — Elara Health',
    linkedCaseId: 'case-003',
    type: 'Evidence',
    evidenceType: 'Link',
    submittedBy: 'Dr. Priya N.',
    source: 'PWA Submission',
    ts: ago(1440),
    content: 'URL to article with inaccuracy shared via PWA. Article archived.',
    _demo: true,
  },
  {
    id: 'evt-005',
    title: 'Customer Post Logged — Oakhaven Hotels',
    linkedCaseId: 'case-004',
    type: 'Evidence',
    evidenceType: 'Public Post',
    submittedBy: 'Sarah K.',
    source: 'PWA Submission',
    ts: ago(720),
    content: 'Instagram post by affected guest with 45K followers. Screenshot archived.',
    _demo: true,
  },
  {
    id: 'evt-006',
    title: 'Risk Level Escalated — Vantage Case',
    linkedCaseId: 'case-002',
    type: 'Escalation',
    evidenceType: 'Internal Note',
    submittedBy: 'Dashboard Admin',
    source: 'Dashboard',
    ts: ago(600),
    content: 'Thread reshares exceeded 2,000. Risk level raised from High to Critical.',
    _demo: true,
  },
  {
    id: 'evt-007',
    title: 'Regulatory Inquiry Received — NordVista',
    linkedCaseId: 'case-005',
    type: 'Evidence',
    evidenceType: 'Internal Note',
    submittedBy: 'James W.',
    source: 'PWA Submission',
    ts: ago(360),
    content: 'Formal inquiry received via certified post. Reference: NVC/REG/2026-041. Acknowledged.',
    _demo: true,
  },
  {
    id: 'evt-008',
    title: 'Monitoring Active — Creator Misquote',
    linkedCaseId: 'case-006',
    type: 'Note',
    evidenceType: 'Note',
    submittedBy: 'Marcus T.',
    source: 'PWA Submission',
    ts: ago(175),
    content: 'Clip circulating on TikTok. Engagement not accelerating. No amplification detected.',
    _demo: true,
  },
]

// ─── DRAFTS — Response Drafts ─────────────────────────────────
export const DEMO_DRAFTS = [
  {
    id: 'draft-001',
    title: 'Holding Statement — Vantage Fintech Social Thread',
    linkedCaseId: 'case-002',
    intendedChannel: 'X (Twitter) — Official Account',
    tone: 'Holding Statement',
    status: 'Needs Review',
    owner: 'Marcus T.',
    aiAdvisory: true,
    content: 'We are aware of the concerns raised online and take all feedback seriously. Our team is reviewing the matter and will provide a full update within 24 hours. We are committed to transparency and are working to address this directly. [DRAFT — HUMAN REVIEW REQUIRED]',
    createdAt: ago(2650),
    updatedAt: ago(120),
    _demo: true,
  },
  {
    id: 'draft-002',
    title: 'Correction Request — Elara Health Press Article',
    linkedCaseId: 'case-003',
    intendedChannel: 'Email to Editor / Publication Contact',
    tone: 'Corrective',
    status: 'Approved',
    owner: 'Dr. Priya N.',
    aiAdvisory: true,
    content: 'Dear [Editor], We write to respectfully request a correction to your article published on [date]. The article states [INACCURACY]. The factual position is [CORRECTION]. We would appreciate an update at your earliest convenience. [DRAFT — APPROVED FOR SEND]',
    createdAt: ago(1400),
    updatedAt: ago(85),
    _demo: true,
  },
  {
    id: 'draft-003',
    title: 'Public Apology — Oakhaven Hotels Guest',
    linkedCaseId: 'case-004',
    intendedChannel: 'Instagram Public Comment + TripAdvisor',
    tone: 'Apologetic',
    status: 'Draft',
    owner: 'Sarah K.',
    aiAdvisory: true,
    content: 'We sincerely apologise for the disruption caused to your wedding booking. This falls far short of the standard we hold ourselves to. We have reached out directly to arrange a personal conversation and to make this right. [DRAFT — NEEDS REVIEW]',
    createdAt: ago(680),
    updatedAt: ago(200),
    _demo: true,
  },
  {
    id: 'draft-004',
    title: 'Investor Update — NordVista Capital',
    linkedCaseId: 'case-005',
    intendedChannel: 'Email — Investor Relations List',
    tone: 'Formal',
    status: 'Legal Review Needed',
    owner: 'James W.',
    aiAdvisory: true,
    content: 'Dear Investors, We wish to proactively inform you of a regulatory inquiry we received on [date]. We are cooperating fully and are confident in our compliance position. Further updates will follow. This communication is confidential. [DRAFT — LEGAL REVIEW REQUIRED]',
    createdAt: ago(330),
    updatedAt: ago(30),
    _demo: true,
  },
]

// ─── STAKEHOLDER UPDATES ──────────────────────────────────────
export const DEMO_UPDATES = [
  {
    id: 'upd-001',
    title: 'Internal Team Briefing — Review Spike',
    linkedCaseId: 'case-001',
    audience: 'Internal Team',
    status: 'Sent',
    owner: 'Dashboard Admin',
    lastSent: ago(200),
    pending: false,
    notes: 'All team members briefed on situation. Monitoring schedule assigned.',
    _demo: true,
  },
  {
    id: 'upd-002',
    title: 'Client Holding Update — Vantage Fintech',
    linkedCaseId: 'case-002',
    audience: 'Client (Vantage Fintech Leadership)',
    status: 'Sent',
    owner: 'Marcus T.',
    lastSent: ago(400),
    pending: false,
    notes: 'Client acknowledged update. Awaiting outcome of legal review.',
    _demo: true,
  },
  {
    id: 'upd-003',
    title: 'PR Team Briefing — Correction Status',
    linkedCaseId: 'case-003',
    audience: 'PR Team',
    status: 'Pending',
    owner: 'Dr. Priya N.',
    lastSent: null,
    pending: true,
    notes: 'Awaiting legal sign-off before sending.',
    _demo: true,
  },
  {
    id: 'upd-004',
    title: 'Leadership Notification — Regulatory Inquiry',
    linkedCaseId: 'case-005',
    audience: 'Executive Leadership',
    status: 'Sent',
    owner: 'James W.',
    lastSent: ago(300),
    pending: false,
    notes: 'Board notified. Confidentiality protocol in place.',
    _demo: true,
  },
  {
    id: 'upd-005',
    title: 'Customer Apology Follow-up — Oakhaven',
    linkedCaseId: 'case-004',
    audience: 'Affected Customer',
    status: 'Pending',
    owner: 'Sarah K.',
    lastSent: null,
    pending: true,
    notes: 'Awaiting draft approval before sending to guest.',
    _demo: true,
  },
]

// ─── FEED — Live Update Feed ──────────────────────────────────
export const DEMO_FEED = [
  {
    id: 'feed-001',
    type: 'task_complete',
    icon: 'CheckCircle',
    color: 'green',
    text: 'Marcus T. confirmed holding statement received',
    sub: 'Vantage Fintech · Task #001',
    ts: ago(72),
    _demo: true,
  },
  {
    id: 'feed-002',
    type: 'evidence',
    icon: 'FileText',
    color: 'gold',
    text: 'Screenshot evidence submitted via Response PWA',
    sub: 'Vantage Fintech viral thread · Marcus T.',
    ts: ago(185),
    _demo: true,
  },
  {
    id: 'feed-003',
    type: 'escalation',
    icon: 'AlertTriangle',
    color: 'red',
    text: 'Risk level escalated to Critical — Vantage Fintech',
    sub: 'Reshares exceeded 2,000 · Dashboard Admin',
    ts: ago(600),
    _demo: true,
  },
  {
    id: 'feed-004',
    type: 'checkin',
    icon: 'UserCheck',
    color: 'green',
    text: 'James W. availability check-in completed',
    sub: 'NordVista Capital · PWA-004',
    ts: ago(110),
    _demo: true,
  },
  {
    id: 'feed-005',
    type: 'draft',
    icon: 'FileEdit',
    color: 'purple',
    text: 'Draft response awaiting approval — Correction Request',
    sub: 'Elara Health · Dr. Priya N.',
    ts: ago(85),
    _demo: true,
  },
  {
    id: 'feed-006',
    type: 'update_sent',
    icon: 'Send',
    color: 'silver',
    text: 'Stakeholder update sent to Vantage Fintech leadership',
    sub: 'Client holding update · Marcus T.',
    ts: ago(400),
    _demo: true,
  },
  {
    id: 'feed-007',
    type: 'task_pending',
    icon: 'Clock',
    color: 'gold',
    text: 'Task pending: Upload evidence — Review screenshots',
    sub: 'Meridian Cafe Group · Sarah K.',
    ts: ago(45),
    _demo: true,
  },
  {
    id: 'feed-008',
    type: 'evidence',
    icon: 'MapPin',
    color: 'gold',
    text: 'Regulatory inquiry reference logged by responder',
    sub: 'NordVista Capital · James W.',
    ts: ago(360),
    _demo: true,
  },
  {
    id: 'feed-009',
    type: 'monitoring',
    icon: 'Eye',
    color: 'silver',
    text: 'Creator misquote clip — no amplification detected',
    sub: 'Layla Voss · Marcus T.',
    ts: ago(175),
    _demo: true,
  },
  {
    id: 'feed-010',
    type: 'task_complete',
    icon: 'CheckCircle',
    color: 'green',
    text: 'Social media issue logged — viral thread archived',
    sub: 'Vantage Fintech · Task #006 · Marcus T.',
    ts: ago(185),
    _demo: true,
  },
]

// ─── Composed export ──────────────────────────────────────────
export const DEMO_DATA = {
  cases:     DEMO_CASES,
  tasks:     DEMO_TASKS,
  pwas:      DEMO_PWAS,
  timeline:  DEMO_TIMELINE,
  drafts:    DEMO_DRAFTS,
  updates:   DEMO_UPDATES,
  feedItems: DEMO_FEED,
}

export default DEMO_DATA

// ============================================================
// TrustSheild Response PWA — Demo Data (Run 3)
// ============================================================
// ⚠️  DEMO DATA ONLY — All records are fictional.
//     Clearly marked as demo/simulation throughout the UI.
// ============================================================

// ─── PWA Demo Profile ─────────────────────────────────────────
export const PWA_DEMO_PROFILE = {
  id:           'pwa-001-demo',
  displayName:  'Sarah K.',
  role:         'PR Lead',
  organisation: 'Meridian Cafe Group / Oakhaven Hotels',
  pwaIdLabel:   'Unique ID — Run 5',
  mode:         'Demo',
  _demo: true,
}

// ─── PWA Active Case Brief ────────────────────────────────────
export const PWA_DEMO_CASE = {
  id:           'case-001',
  title:        'Negative Review Spike — Meridian Cafe',
  client:       'Meridian Cafe Group',
  riskLevel:    'High',
  source:       'Review Platform',
  channel:      'Google Reviews / Yelp',
  status:       'Action Needed',
  priority:     'High',
  latestInstruction: 'Submit current situation update. Upload screenshots of new reviews. Confirm you have received the holding brief.',
  dashboardOwner:    'Dashboard Admin',
  updatedAt:    ago(45),
  _demo: true,
}

// ─── PWA Tasks ───────────────────────────────────────────────
export const PWA_DEMO_TASKS = [
  {
    id: 'ptask-001',
    title: 'Confirm: Holding Brief Received',
    type: 'Confirm Update Received',
    priority: 'High',
    status: 'New',
    linkedCase: 'Negative Review Spike — Meridian Cafe',
    dueLabel: 'ASAP',
    description: 'Confirm you have received and read the holding brief sent by the dashboard team.',
    _demo: true,
  },
  {
    id: 'ptask-002',
    title: 'Submit Situation Update',
    type: 'Submit Situation Update',
    priority: 'High',
    status: 'In Progress',
    linkedCase: 'Negative Review Spike — Meridian Cafe',
    dueLabel: 'Today',
    description: 'Provide an update on the current on-site situation. Include any new developments observed.',
    _demo: true,
  },
  {
    id: 'ptask-003',
    title: 'Upload Evidence — Screenshots of New Reviews',
    type: 'Upload Evidence / Notes',
    priority: 'Medium',
    status: 'New',
    linkedCase: 'Negative Review Spike — Meridian Cafe',
    dueLabel: 'Today',
    description: 'Take screenshots of all new 1-star reviews and add as evidence notes below.',
    _demo: true,
  },
  {
    id: 'ptask-004',
    title: 'Review Draft Response — Customer Apology',
    type: 'Review Draft Response',
    priority: 'High',
    status: 'Needs Review',
    linkedCase: 'Negative Review Spike — Meridian Cafe',
    dueLabel: 'Before 5pm',
    description: 'Review the draft public response prepared by the dashboard team. Approve, request changes, or escalate for legal review.',
    _demo: true,
  },
  {
    id: 'ptask-005',
    title: 'Log Customer Complaint — Table 7 Incident',
    type: 'Log Customer / Social Issue',
    priority: 'Medium',
    status: 'Complete',
    linkedCase: 'Negative Review Spike — Meridian Cafe',
    dueLabel: 'Done',
    description: 'Log the customer complaint received verbally about table 7 service failure.',
    _demo: true,
  },
]

// ─── PWA Situation Updates (submitted history) ────────────────
export const PWA_DEMO_UPDATES = [
  {
    id: 'pupd-001',
    type: 'Situation Update',
    message: 'Spoke with manager on site. Three staff members confirm the review cluster started after a staff dispute was discussed on a private Facebook group. Monitoring.',
    urgency: 'Medium',
    linkedCase: 'Negative Review Spike — Meridian Cafe',
    submittedBy: 'Sarah K.',
    ts: ago(200),
    status: 'Submitted (Demo)',
    _demo: true,
  },
  {
    id: 'pupd-002',
    type: 'Check-in',
    message: 'Available and monitoring situation. No new public posts in last 2 hours.',
    urgency: 'Low',
    linkedCase: 'Negative Review Spike — Meridian Cafe',
    submittedBy: 'Sarah K.',
    ts: ago(90),
    status: 'Submitted (Demo)',
    _demo: true,
  },
]

// ─── PWA Evidence Notes ───────────────────────────────────────
export const PWA_DEMO_NOTES = [
  {
    id: 'pnote-001',
    evidenceType: 'Internal Note',
    description: 'Confirmed with manager: 14 new reviews since Monday. All accounts appear newly created with no prior activity.',
    linkedCase: 'Negative Review Spike — Meridian Cafe',
    submittedBy: 'Sarah K.',
    ts: ago(250),
    _demo: true,
  },
  {
    id: 'pnote-002',
    evidenceType: 'Customer Message',
    description: 'Customer contacted directly via email — willing to update review once issue is resolved. Flagged for follow-up.',
    linkedCase: 'Negative Review Spike — Meridian Cafe',
    submittedBy: 'Sarah K.',
    ts: ago(130),
    _demo: true,
  },
]

// ─── PWA Draft Reviews ────────────────────────────────────────
export const PWA_DEMO_DRAFT_REVIEWS = [
  {
    id: 'pdraft-001',
    title: 'Public Response — Negative Review Spike',
    intendedChannel: 'Google Reviews — Owner Response',
    tone: 'Apologetic',
    status: 'Awaiting Your Review',
    linkedCase: 'Negative Review Spike — Meridian Cafe',
    content: 'We sincerely apologise for any experience that has fallen short of our standards at Meridian Cafe. We take all feedback very seriously and our team is actively investigating. We are committed to improving and would welcome the opportunity to resolve this directly. Please contact us at [contact]. [DRAFT — HUMAN REVIEW REQUIRED BEFORE POSTING]',
    reviewStatus: null, // null | 'approved' | 'needs_changes' | 'escalated'
    dashboardNote: 'Please review and approve this draft before it is posted publicly. If legal review is needed, please escalate.',
    _demo: true,
  },
]

// ─── PWA Escalations (history) ────────────────────────────────
export const PWA_DEMO_ESCALATIONS = [
  {
    id: 'pesc-001',
    reason: 'PR review needed',
    urgency: 'High',
    message: 'Review cluster appears coordinated. Recommend PR team review before any public response is posted.',
    submittedBy: 'Sarah K.',
    ts: ago(300),
    status: 'Submitted (Demo)',
    _demo: true,
  },
]

// ─── PWA Demo Composed export ─────────────────────────────────
export const PWA_DEMO_DATA = {
  profile:          PWA_DEMO_PROFILE,
  pwaCase:          PWA_DEMO_CASE,
  pwaTasks:         PWA_DEMO_TASKS,
  pwaUpdates:       PWA_DEMO_UPDATES,
  pwaNotes:         PWA_DEMO_NOTES,
  pwaDraftReviews:  PWA_DEMO_DRAFT_REVIEWS,
  pwaEscalations:   PWA_DEMO_ESCALATIONS,
}

export default DEMO_DATA

// ============================================================
// TrustSheild OS™ — Configurable Task System Seed (Run 4)
// ============================================================
// ⚠️  DEMO DATA ONLY — All records are fictional.
//     trustsheild_tasks key — shared between dashboard & PWA.
// ============================================================

// ─── Demo PWA Contacts (Run 5 will replace with real IDs) ────
export const DEMO_PWA_CONTACTS = [
  { id: 'pwa-001', displayName: 'Sarah K.',        role: 'PR Lead',            avatar: 'SK', syncStatus: 'Demo', org: 'Meridian Cafe / Oakhaven Hotels' },
  { id: 'pwa-002', displayName: 'Marcus T.',        role: 'Responder',          avatar: 'MT', syncStatus: 'Demo', org: 'Vantage Fintech / Layla Voss' },
  { id: 'pwa-003', displayName: 'Dr. Priya N.',     role: 'Legal Contact',      avatar: 'PN', syncStatus: 'Pending', org: 'Elara Health / Sable Agency' },
  { id: 'pwa-004', displayName: 'James W.',         role: 'Staff Member',       avatar: 'JW', syncStatus: 'Demo', org: 'NordVista Capital' },
  { id: 'pwa-005', displayName: 'Agency Contact',   role: 'Agency Lead',        avatar: 'AC', syncStatus: 'Offline', org: 'Sable & Partners' },
]

// ─── Task Templates ───────────────────────────────────────────
export const TASK_TEMPLATES = [
  {
    id: 'tmpl-001',
    name: 'Negative Review Spike Response',
    description: 'Assign to the PR lead to confirm briefing received, submit a situation update, and upload evidence screenshots.',
    type: 'Submit Situation Update',
    priority: 'High',
    dueStatus: 'Due Soon',
    instructions: 'Please confirm you have received this brief, submit a current situation update, and upload screenshots of any new reviews.',
    requiredAction: 'Confirm receipt, submit update, upload evidence',
    humanReviewRequired: true,
    icon: 'Star',
    color: '#fb923c',
  },
  {
    id: 'tmpl-002',
    name: 'Social Media Complaint Escalation',
    description: 'Request escalation review when a social media complaint is gaining traction and requires PR or legal attention.',
    type: 'Request Escalation',
    priority: 'Critical',
    dueStatus: 'Urgent',
    instructions: 'The social media situation is escalating. Please review the thread, log any new evidence, and request escalation if legal or PR review is needed.',
    requiredAction: 'Request escalation with supporting notes',
    humanReviewRequired: true,
    icon: 'AlertTriangle',
    color: '#f87171',
  },
  {
    id: 'tmpl-003',
    name: 'Draft Statement Approval',
    description: 'Ask the assigned responder to review and approve or request changes on a prepared draft response.',
    type: 'Approve Draft Response',
    priority: 'High',
    dueStatus: 'Due Soon',
    instructions: 'A draft response has been prepared. Please review it carefully and indicate whether you approve it for use, request changes, or need legal escalation.',
    requiredAction: 'Approve, request changes, or escalate',
    humanReviewRequired: true,
    icon: 'FileEdit',
    color: '#a78bfa',
  },
  {
    id: 'tmpl-004',
    name: 'Customer Complaint Follow-up',
    description: 'Ask the contact to log new customer complaint details and provide a situation update.',
    type: 'Log Customer / Social Issue',
    priority: 'Medium',
    dueStatus: 'Due Soon',
    instructions: 'Please log the details of any new customer complaints received and submit a brief situation update.',
    requiredAction: 'Log complaint and submit update',
    humanReviewRequired: false,
    icon: 'MessageCircle',
    color: '#fbbf24',
  },
  {
    id: 'tmpl-005',
    name: 'Legal Review Request',
    description: 'Assign to a legal or compliance contact for legal review of a situation or proposed response.',
    type: 'Legal/PR Review Request',
    priority: 'High',
    dueStatus: 'Urgent',
    instructions: 'Legal review is required. Please assess the situation and provide your guidance before any public response is issued.',
    requiredAction: 'Provide legal guidance or escalate',
    humanReviewRequired: true,
    icon: 'Scale',
    color: '#f87171',
  },
  {
    id: 'tmpl-006',
    name: 'Stakeholder Update Confirmation',
    description: 'Confirm that a stakeholder update has been received and acknowledged by the contact.',
    type: 'Confirm Stakeholder Update',
    priority: 'Medium',
    dueStatus: 'No Due Date',
    instructions: 'Please confirm you have received and read the stakeholder update and acknowledge receipt.',
    requiredAction: 'Confirm receipt',
    humanReviewRequired: false,
    icon: 'CheckCircle',
    color: '#37ff8b',
  },
  {
    id: 'tmpl-007',
    name: 'Evidence Collection Request',
    description: 'Request the contact to collect and submit specific evidence items.',
    type: 'Add Evidence / Note',
    priority: 'Medium',
    dueStatus: 'Due Soon',
    instructions: 'Please collect and log the requested evidence items. Include screenshots, notes, or links as appropriate.',
    requiredAction: 'Submit evidence notes',
    humanReviewRequired: false,
    icon: 'FileText',
    color: '#d6a84f',
  },
  {
    id: 'tmpl-008',
    name: 'Public Claim Correction Review',
    description: 'Request review of a factual inaccuracy in public coverage and approval of a correction response.',
    type: 'Approve Draft Response',
    priority: 'High',
    dueStatus: 'Due Soon',
    instructions: 'A factual correction response has been drafted. Please review it for accuracy and approve or request changes before it is submitted.',
    requiredAction: 'Approve or request changes',
    humanReviewRequired: true,
    icon: 'Edit3',
    color: '#38bdf8',
  },
  {
    id: 'tmpl-009',
    name: 'Urgent Holding Statement Review',
    description: 'Urgent review of a holding statement before it is published.',
    type: 'Review Draft Response',
    priority: 'Critical',
    dueStatus: 'Urgent',
    instructions: 'A holding statement has been prepared for urgent review. This must be approved by a responsible human before any publication.',
    requiredAction: 'Approve or escalate immediately',
    humanReviewRequired: true,
    icon: 'Zap',
    color: '#f87171',
  },
  {
    id: 'tmpl-010',
    name: 'Reputation Recovery Follow-up',
    description: 'Follow-up action to confirm recovery steps are being taken after a resolved crisis.',
    type: 'Internal Follow-up',
    priority: 'Low',
    dueStatus: 'No Due Date',
    instructions: 'Please confirm the agreed recovery steps have been completed and provide a brief status note.',
    requiredAction: 'Submit recovery status update',
    humanReviewRequired: false,
    icon: 'TrendingUp',
    color: '#37ff8b',
  },
]

// ─── Seed Configurable Tasks ──────────────────────────────────
export const SEED_CONFIG_TASKS = [
  {
    id: 'tsk-seed-001',
    title: 'Approve Draft Statement — Vantage Fintech',
    type: 'Approve Draft Response',
    linkedCaseId: 'case-002',
    linkedCaseTitle: 'Social Media Complaint Gaining Traction',
    assignedPwaId: 'pwa-002',
    assignedName: 'Marcus T.',
    assignedRole: 'Responder',
    priority: 'Critical',
    dueStatus: 'Urgent',
    instructions: 'A holding statement has been prepared for the Vantage Fintech viral thread. Review it carefully and approve or request changes. Legal team must be looped in if needed.',
    requiredAction: 'Approve, request changes, or escalate to legal',
    humanReviewRequired: true,
    status: 'Sent to PWA',
    source: 'demo',
    createdBy: 'TrustSheild Command Dashboard',
    createdAt: ago(95),
    updatedAt: ago(40),
    lastPwaAction: null,
    _demo: true,
  },
  {
    id: 'tsk-seed-002',
    title: 'Submit Situation Update — Review Spike',
    type: 'Submit Situation Update',
    linkedCaseId: 'case-001',
    linkedCaseTitle: 'Negative Review Spike — Meridian Cafe',
    assignedPwaId: 'pwa-001',
    assignedName: 'Sarah K.',
    assignedRole: 'PR Lead',
    priority: 'High',
    dueStatus: 'Due Soon',
    instructions: 'The dashboard needs an updated situation report from the on-site team. Please submit a current update with any new information about the review cluster.',
    requiredAction: 'Submit situation update',
    humanReviewRequired: false,
    status: 'In Progress',
    source: 'demo',
    createdBy: 'TrustSheild Command Dashboard',
    createdAt: ago(120),
    updatedAt: ago(60),
    lastPwaAction: 'In Progress',
    _demo: true,
  },
  {
    id: 'tsk-seed-003',
    title: 'Legal Review — Regulatory Inquiry Disclosure',
    type: 'Legal/PR Review Request',
    linkedCaseId: 'case-005',
    linkedCaseTitle: 'Internal Incident — Controlled Stakeholder Update',
    assignedPwaId: 'pwa-004',
    assignedName: 'James W.',
    assignedRole: 'Staff Member',
    priority: 'High',
    dueStatus: 'Urgent',
    instructions: 'Regulatory inquiry received. Please confirm you have received this briefing and flag any concerns immediately. Do not discuss externally without authorisation.',
    requiredAction: 'Confirm receipt and flag any concerns',
    humanReviewRequired: true,
    status: 'Received',
    source: 'demo',
    createdBy: 'TrustSheild Command Dashboard',
    createdAt: ago(200),
    updatedAt: ago(110),
    lastPwaAction: 'Received',
    _demo: true,
  },
  {
    id: 'tsk-seed-004',
    title: 'Approve Correction Response — Elara Health',
    type: 'Approve Draft Response',
    linkedCaseId: 'case-003',
    linkedCaseTitle: 'Incorrect Public Claim — Press Coverage',
    assignedPwaId: 'pwa-003',
    assignedName: 'Dr. Priya N.',
    assignedRole: 'Legal Contact',
    priority: 'High',
    dueStatus: 'Due Soon',
    instructions: 'The correction response to the press inaccuracy has been finalised. Please review for accuracy and provide sign-off. Do not publish without your approval.',
    requiredAction: 'Approve or request changes',
    humanReviewRequired: true,
    status: 'Sent to PWA',
    source: 'demo',
    createdBy: 'TrustSheild Command Dashboard',
    createdAt: ago(80),
    updatedAt: ago(80),
    lastPwaAction: null,
    _demo: true,
  },
  {
    id: 'tsk-seed-005',
    title: 'Log Customer Feedback — Hotel Guest Incident',
    type: 'Log Customer / Social Issue',
    linkedCaseId: 'case-004',
    linkedCaseTitle: 'Customer Service Failure — Oakhaven Hotels',
    assignedPwaId: 'pwa-001',
    assignedName: 'Sarah K.',
    assignedRole: 'PR Lead',
    priority: 'Medium',
    dueStatus: 'No Due Date',
    instructions: 'Please log the full details of the affected guest complaint, including any direct messages received and the timeline of events.',
    requiredAction: 'Log all customer feedback notes',
    humanReviewRequired: false,
    status: 'Complete',
    source: 'demo',
    createdBy: 'TrustSheild Command Dashboard',
    createdAt: ago(300),
    updatedAt: ago(150),
    lastPwaAction: 'Complete',
    _demo: true,
  },
]

// ─── Seed Task Activity ───────────────────────────────────────
export const SEED_TASK_ACTIVITY = [
  { id: 'tact-001', ts: ago(95),  type: 'task_created', icon: 'Plus',          color: 'gold',   text: 'Task created: Approve Draft Statement — Vantage Fintech', sub: 'Assigned to Marcus T. · Approve Draft Response', taskId: 'tsk-seed-001', _demo: true },
  { id: 'tact-002', ts: ago(120), type: 'task_created', icon: 'Plus',          color: 'gold',   text: 'Task created: Submit Situation Update — Review Spike',     sub: 'Assigned to Sarah K. · Submit Situation Update',   taskId: 'tsk-seed-002', _demo: true },
  { id: 'tact-003', ts: ago(200), type: 'task_created', icon: 'Plus',          color: 'gold',   text: 'Task created: Legal Review — Regulatory Inquiry',         sub: 'Assigned to James W. · Legal/PR Review Request',   taskId: 'tsk-seed-003', _demo: true },
  { id: 'tact-004', ts: ago(110), type: 'pwa_action',   icon: 'CheckCircle',   color: 'green',  text: 'PWA confirmed task received',                             sub: '"Legal Review — Regulatory Inquiry" · James W.',   taskId: 'tsk-seed-003', _demo: true },
  { id: 'tact-005', ts: ago(60),  type: 'pwa_action',   icon: 'Play',          color: 'gold',   text: 'PWA started task',                                        sub: '"Submit Situation Update" · Sarah K.',             taskId: 'tsk-seed-002', _demo: true },
  { id: 'tact-006', ts: ago(80),  type: 'task_created', icon: 'Plus',          color: 'gold',   text: 'Task created: Approve Correction Response — Elara Health',sub: 'Assigned to Dr. Priya N. · Approve Draft Response', taskId: 'tsk-seed-004', _demo: true },
  { id: 'tact-007', ts: ago(300), type: 'task_created', icon: 'Plus',          color: 'gold',   text: 'Task created: Log Customer Feedback — Hotel Guest',       sub: 'Assigned to Sarah K. · Log Customer / Social Issue', taskId: 'tsk-seed-005', _demo: true },
  { id: 'tact-008', ts: ago(150), type: 'pwa_action',   icon: 'CheckSquare',   color: 'green',  text: 'Task marked complete by PWA',                             sub: '"Log Customer Feedback" · Sarah K.',               taskId: 'tsk-seed-005', _demo: true },
]

// ─── Composed task data export ────────────────────────────────
export const TASK_SEED_DATA = {
  configTasks:  SEED_CONFIG_TASKS,
  taskActivity: SEED_TASK_ACTIVITY,
  pwaContacts:  DEMO_PWA_CONTACTS,
}

export { TASK_TEMPLATES }
